import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  searchComponent: {
    margin: 2,
  },
  header: { 
    flexDirection: 'row',
    alignItems: 'center',
    padding: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  headerText: {
    fontSize: 48,
    fontWeight: 'bold',
  },  
  container: {
    backgroundColor: 'white',
    overflow: 'hidden',
    alignContent: 'center',
    alignItems: 'center',
  },
  letterContainer: {
    flexDirection: 'column',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
    padding: 8,
  },
  mutedText: {
    color: '#aaa',
    fontSize: 12,
  },
  showDataComponent: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    elevation: 7,
    left: 500,
    backgroundColor: '#fff',
    padding: 0,
  },
  centeredViewModal: {
    flex: 1,
    alignItems: 'center',
    position: 'absolute',
    width: '100%',
    height: '100%',
  },
  modalView: {
    backgroundColor: 'white',
    borderRadius: 20,
    width: '98%',
    paddingHorizontal: 20,
    marginBottom: 10,
    paddingVertical: 20,
    alignItems: 'center',
    position: 'absolute',
    bottom: 10,
  },
  AddCenteredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    bottom: 0,
    width: '100%',
    height: '0%',
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    bottom: 0,
    width: '100%',
    height: '0%',
  },
  AddBtn: {
    backgroundColor: '#101e5a',
    padding: 16,
    borderRadius: 100,
    position: 'absolute',
    bottom: 24,
    elevation: 8,
  },
  flex1Center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    padding: 8,
  },
  flex2Center: {
    flex: 2,
    justifyContent: 'flex-start',
    alignItems: 'center',
    padding: 8,
  },
  txtInput: {
    width: '100%',
    fontSize: 16,
    alignSelf: 'center',
    padding: 10,
    backgroundColor: '#e6e8f1',
    marginBottom: 10,
  },
  textContainer: {
    flexDirection: 'row',
  },
  priceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  barCodeIcon: {
    color: '#101e5a',
    flex: 1,
    fontSize: 28,
  },
  nombre: {
    flex: 9,
    fontSize: 28,
    fontWeight: 'bold',
    color: '#101e5a',
    padding: 4,
  },
  nombreContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    justifyContent: 'flex-start',
    borderColor: '#ccc',
  },
  editNombre: {
    flex: 1,
    textAlign: 'center',
    color: '#101e5a',
    paddingHorizontal: 8,
  },
  quantity: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  quantityBadge: {
    width: 24,
    height: 24,
    backgroundColor: '#e6e8f1',
    textAlign: 'center',
    textAlignVertical: 'center',
    borderRadius: 100,
    color: '#000',
  },
  listItem: {
    width: '90%',
    height: 100,
    overflow: 'hidden',
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  listItemImage: {
    height: '100%',
    width: '100%',
    resizeMode: 'contain',
    borderRadius: 8,
  },
  modifyQuantityContainer: {
    width: 36,
    alignItems: 'center',
    justifyContent: 'center',
    height: 36,
  },
  listItemQuantity: {
    width: 18,
    height: 18,
    padding: 2,
    marginRight: 8,
    borderRadius: 100,
    backgroundColor: '#ddd',
    alignItems: 'center',
    justifyContent: 'center',
  },
  itemTitle: {
    fontSize: 14,
    overflow: 'hidden',
  },
  itemSubtitle: {
    fontSize: 12,
    color: '#b4b6be',
    overflow: 'hidden',
  },
  form: {
    paddingHorizontal: 8,
  },  
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#00000055',
  },
  imageContainer: {
    alignItems: 'center',
    alignContent: 'center',
    alignSelf: 'center',
    position: 'relative',
    height: 260,
    width: '100%',
    marginVertical: 10,
  },
  showImageButton: {
    alignItems: 'center',
    alignContent: 'center',
    width: '100%',
    height: '100%',
    backgroundColor: '#f1f2f3',
    zIndex: -1,
    overflow: 'hidden',
  },
  updateImageButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: '#f6f7f8aa',
    borderRadius: 100,
    padding: 10,
    elevation: 30,
  },
  addImageIcon: {
    fontSize: 225,
    color: '#101e5a',
  },
  image: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  displayImage: {
    width: '100%',
    height: '100%',
  },
  displayImageContainer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#000',
  },
  displayCloseIcon: {
    position: 'absolute',
    top: 8,
    left: 8,
    zIndex: 100,
    elevation: 30,
  },
  listTitle: {
    color: 'darkgray',
    fontSize: 24,
    height: 30,
    width: '100%',
    textAlign: 'center',
    textAlignVertical: 'center',
    borderWidth: 1,
    fontWeight: 'bold',
  },
  listGroupContainer: {
    borderBottomWidth: 0.5,
    borderColor: '#eee',
    backgroundColor: 'white',
  }
});

export default styles;
