const Ventas = [
  {
    listaProductos: [
      {
        cantidad: 20,
        nombre: 'Baymax',
        pid: '0386',
        refId: '3omxdK59wUAdmaOFPQZc',
        uid: 'QSdEwPeAUXTyaOrQefMIeOMu9j72',
        valorInvertidoP_U: 15,
        valorInvertidoP_M: 10,
        valorVentaP_U: 30,
        valorVentaP_M: 25,
        masa: false,
        gananciaP_U: 15,
        gananciaP_M: 15,
        proveedor: 'Grupo Intur',
      },
      {
        cantidad: 20,
        nombre: 'Sandia',
        pid: '1234',
        refId: '3omxdK59wUAdmaOFPQZc',
        uid: 'QSdEwPeAUXTyaOrQefMIeOMu9j72',
        valorInvertidoP_U: 15,
        valorInvertidoP_M: 10,
        valorVentaP_U: 30,
        valorVentaP_M: 25,
        masa: true,
        gananciaP_U: 15,
        gananciaP_M: 15,
        proveedor: 'Joann Murillo',
      },
      {
        cantidad: 0,
        nombre: 'Escandalosos',
        pid: '0440',
        refId: 'CDixpRjasuom4Xw41HnR',
        uid: 'm19nhLJ0rzeRbm6BgoluY8oLsAT2',
        valorInvertidoP_U: 120,
        valorInvertidoP_M: 100,
        valorVentaP_U: 180,
        valorVentaP_M: 150,
        gananciaP_U: 60,
        gananciaP_M: 50,
        masa: false,
        proveedor: 'Carlos Carias',
      },
    ],
    totalVenta: 240,
    fechaCorta: '02-06-2020',
    fechaLarga: '02 de junio del 2020',
  },
  {
    listaProductos: [
      {
        cantidad: 20,
        nombre: 'Baymax',
        pid: '0386',
        refId: '3omxdK59wUAdmaOFPQZc',
        uid: 'QSdEwPeAUXTyaOrQefMIeOMu9j72',
        valorInvertidoP_U: 15,
        valorInvertidoP_M: 10,
        valorVentaP_U: 30,
        valorVentaP_M: 25,
        masa: false,
        gananciaP_U: 15,
        gananciaP_M: 15,
        proveedor: 'Grupo Intur',
      },
      {
        cantidad: 20,
        nombre: 'Sandia',
        pid: '1234',
        refId: '3omxdK59wUAdmaOFPQZc',
        uid: 'QSdEwPeAUXTyaOrQefMIeOMu9j72',
        valorInvertidoP_U: 15,
        valorInvertidoP_M: 10,
        valorVentaP_U: 30,
        valorVentaP_M: 25,
        masa: true,
        gananciaP_U: 15,
        gananciaP_M: 15,
        proveedor: 'Joann Murillo',
      },
      {
        cantidad: 0,
        nombre: 'Escandalosos',
        pid: '0440',
        refId: 'CDixpRjasuom4Xw41HnR',
        uid: 'm19nhLJ0rzeRbm6BgoluY8oLsAT2',
        valorInvertidoP_U: 120,
        valorInvertidoP_M: 100,
        valorVentaP_U: 180,
        valorVentaP_M: 150,
        gananciaP_U: 60,
        gananciaP_M: 50,
        masa: false,
        proveedor: 'Carlos Carias',
      },
    ],
    totalVenta: 240,
    fechaCorta: '02-06-2020',
    fechaLarga: '02 de junio del 2020',
  },
];

const ClientsData = [
  {
    id: 'asdjfqiuy4a3',
    nombre: 'John Doe',
    telefono: '',
    email: 'johndoe@gmail.com',
    comentario: '',
  },
  {
    id: 'faq2qwrq34',
    nombre: 'Carl Doe',
    telefono: '3234-2435',
    email: 'carldoe@gmail.com',
    comentario: '',
  },
];

const ProvidersData = [
  {
    id: 'asdjfqiuy4a3',
    nombre: 'Grupo intur',
    telefono: '2440-8960',
    email: 'grupointur@gmail.com',
    comentario: 'Mayorista',
  },
  {
    id: 'faq2qwrq34',
    nombre: 'Carlos Carias',
    telefono: '3456-2435',
    email: 'calocar@gmail.com',
    comentario: 'Vendedor de panes ambulante',
  },
  {
    id: 'geofdnsgodfng',
    nombre: 'Joann Murillo',
    telefono: '3565-2546',
    email: 'joannmurillo@gmail.com',
    comentario: 'Vendedor de verduras',
  },
];

const ProductData = [
  {
    cantidad: 20,
    nombre: 'Baymax',
    pid: '0386',
    refId: '3omxdK59wUAdmaOFPQZc',
    uid: 'QSdEwPeAUXTyaOrQefMIeOMu9j72',
    valorInvertidoP_U: 15,
    valorInvertidoP_M: 10,
    valorVentaP_U: 30,
    valorVentaP_M: 25,
    masa: false,
    gananciaP_U: 15,
    gananciaP_M: 15,
    proveedor: 'Grupo Intur',
  },
  {
    cantidad: 20,
    nombre: 'Sandia',
    pid: '1234',
    refId: '3omxdK59wUAdmaOFPQZc',
    uid: 'QSdEwPeAUXTyaOrQefMIeOMu9j72',
    valorInvertidoP_U: 15,
    valorInvertidoP_M: 10,
    valorVentaP_U: 30,
    valorVentaP_M: 25,
    masa: true,
    gananciaP_U: 15,
    gananciaP_M: 15,
    proveedor: 'Joann Murillo',
  },
  {
    cantidad: 0,
    nombre: 'Escandalosos',
    pid: '0440',
    refId: 'CDixpRjasuom4Xw41HnR',
    uid: 'm19nhLJ0rzeRbm6BgoluY8oLsAT2',
    valorInvertidoP_U: 120,
    valorInvertidoP_M: 100,
    valorVentaP_U: 180,
    valorVentaP_M: 150,
    gananciaP_U: 60,
    gananciaP_M: 50,
    masa: false,
    proveedor: 'Carlos Carias',
  },
];

const ServicesData = [
  {
    cantidad: 20,
    nombre: 'Baymax',
    pid: '0386',
    refId: '3omxdK59wUAdmaOFPQZc',
    uid: 'QSdEwPeAUXTyaOrQefMIeOMu9j72',
    valorInvertidoP_U: 15,
    valorInvertidoP_M: 10,
    valorVentaP_U: 30,
    valorVentaP_M: 25,
    masa: false,
    gananciaP_U: 15,
    gananciaP_M: 15,
    proveedor: 'Grupo Intur',
  },
  {
    cantidad: 20,
    nombre: 'Sandia',
    pid: '1234',
    refId: '3omxdK59wUAdmaOFPQZc',
    uid: 'QSdEwPeAUXTyaOrQefMIeOMu9j72',
    valorInvertidoP_U: 15,
    valorInvertidoP_M: 10,
    valorVentaP_U: 30,
    valorVentaP_M: 25,
    masa: true,
    gananciaP_U: 15,
    gananciaP_M: 15,
    proveedor: 'Joann Murillo',
  },
  {
    cantidad: 0,
    nombre: 'Escandalosos',
    pid: '0440',
    refId: 'CDixpRjasuom4Xw41HnR',
    uid: 'm19nhLJ0rzeRbm6BgoluY8oLsAT2',
    valorInvertidoP_U: 120,
    valorInvertidoP_M: 100,
    valorVentaP_U: 180,
    valorVentaP_M: 150,
    gananciaP_U: 60,
    gananciaP_M: 50,
    masa: false,
    proveedor: 'Carlos Carias',
  },
];

const FormOptions = [
  {
    name: 'Agregar cliente',
    icon: 'favorite',
    funcType: 'ADD_CLIENT',
    type: 'Clientes',
  },
  {
    name: 'Agregar producto',
    icon: 'shopping-basket',
    funcType: 'ADD_PRODUCT',
    type: 'Productos',
  },
  {
    name: 'Agregar Servicio',
    icon: 'loyalty',
    funcType: 'ADD_SERVICE',
    type: 'Servicios Adicionales',
  },
  {
    name: 'Agregar Proveedor',
    icon: 'assignment-ind',
    funcType: 'ADD_PROVIDER',
    type: 'Proveedores',
  },
];

const Badge = 'Lps.';

export {
  ProductData,
  Ventas,
  FormOptions,
  Badge,
  ClientsData,
  ProvidersData,
  ServicesData,
};
